export const addProps = [
  { name: 'isUpdate', full: !1, default: !1 },
  { name: 'updateId', full: !1, default: 0 },
  { name: 'dialogTitle', full: !1, default: '添加' },
  { name: 'visible', full: !0, default: !1 },
  { name: 'title', full: !0, default: '' },
  { name: 'hasGuard', full: !0, default: 1 },
  { name: 'guardName', full: !0, default: '' },
  { name: 'guardTags', full: !0, default: '' },
  { name: 'guardAvatar', full: !0, default: '' },
  { name: 'guardAvatars', full: !0, default: () => [] },
  { name: 'guardIntro', full: !0, default: '' },
  { name: 'guardBtn', full: !0, default: '' },
  { name: 'attachCover', full: !0, default: '' },
  { name: 'attachCovers', full: !0, default: () => [] },
  { name: 'shareImage', full: !0, default: '' },
  { name: 'shareImages', full: !0, default: () => [] },
  { name: 'publishDate', full: !0, default: '' },
  { name: 'endDate', full: !0, default: '' },
  { name: 'wishCount', full: !0, default: '' },
  { name: 'priority', full: !0, default: '' },
  { name: 'hide', full: !0, default: 0 },
];

export default {};
