export const list = {
  msg: '',
  errorCode: 0,
  data: {
    list: [
      {
        id: 9,
        price: 3342,
        titleType: 1,
        invoiceType: 1,
        invoiceCompany: '测试公司',
        ratepayingNo: 134,
        bankName: '开户行',
        bankNo: 1234,
        registerAddress: '测试地址',
        registerMobile: 12341,
        note: '备注',
        status: 1,
        addTime: '2020-07-09 16:16:21',
        updateTime: '2020-07-09 16:17:21',
        templeId: 4,
        templeName: '幺零零',
      },
      {
        id: 6,
        price: 3342,
        titleType: 1,
        invoiceType: 1,
        invoiceCompany: '测试公司',
        ratepayingNo: 134,
        bankName: '开户行',
        bankNo: 1234,
        registerAddress: '测试地址',
        registerMobile: 12341,
        note: '备注',
        status: 1,
        addTime: '2020-07-09 16:16:21',
        updateTime: '2020-07-09 16:17:21',
        templeId: 4,
        templeName: '幺零零',
      },
      {
        id: 5,
        price: 3342,
        titleType: 1,
        invoiceType: 1,
        invoiceCompany: '测试公司',
        ratepayingNo: 134,
        bankName: '开户行',
        bankNo: 1234,
        registerAddress: '测试地址',
        registerMobile: 12341,
        note: '备注',
        status: 1,
        addTime: '2020-07-09 16:16:21',
        updateTime: '2020-07-09 16:17:21',
        templeId: 4,
        templeName: '幺零零',
      },
    ],
    total: 125,
  },
};

export const uploadInvoice = {
  msg: '',
  errorCode: 0,
  data: '',
};

export const cancelInvoice = {
  msg: '',
  errorCode: 0,
  data: '',
};
