export const list = {
  msg: '',
  errorCode: 0,
  data: [
    {
      channel: 'android',
      activationPeopleNum: 0,
      registerPeopleNum: 0,
      registerFirstPayPeopleNum: 0,
      registerFirstPayPrice: '0.00',
      registerPayNum: 0,
      registerPayPrice: '0.00',
      firstPayPeopleNum: 0,

      firstPayPrice: '0.00',
      PayPeopleNum: 0,
      PayPrice: '0.00',
    },
    {
      channel: '360sjzs_10002',
      activationPeopleNum: 0,
      registerPeopleNum: 0,
      registerFirstPayPeopleNum: 0,
      registerFirstPayPrice: '0.00',
      registerPayNum: 0,
      registerPayPrice: '0.00',
      firstPayPeopleNum: 0,
      firstPayPrice: '0.00',
      PayPeopleNum: 0,
      PayPrice: '0.00',
    },
    {
      channel: 'sample',
      activationPeopleNum: 0,
      registerPeopleNum: 0,
      registerFirstPayPeopleNum: 0,
      registerFirstPayPrice: '0.00',
      registerPayNum: 0,
      registerPayPrice: '0.00',
      firstPayPeopleNum: 0,
      firstPayPrice: '0.00',
      PayPeopleNum: 0,
      PayPrice: '0.00',
    },
    {
      channel: 'all_0',
      activationPeopleNum: 6,
      registerPeopleNum: 6,
      registerFirstPayPeopleNum: 1,
      registerFirstPayPrice: '0.01',
      registerPayNum: 4,
      registerPayPrice: '0.04',
      firstPayPeopleNum: 3,
      firstPayPrice: '0.03',
      PayPeopleNum: 8,
      PayPrice: '0.08',
    },
    {
      channel: 'appstore',
      activationPeopleNum: 11,
      registerPeopleNum: 11,
      registerFirstPayPeopleNum: 0,
      registerFirstPayPrice: '0.00',
      registerPayNum: 0,
      registerPayPrice: '0.00',
      firstPayPeopleNum: 1,
      firstPayPrice: '0.01',
      PayPeopleNum: 147,
      PayPrice: '1.64',
    },
    {
      channel: 'debug',
      activationPeopleNum: 1,
      registerPeopleNum: 1,
      registerFirstPayPeopleNum: 0,
      registerFirstPayPrice: '0.00',
      registerPayNum: 0,
      registerPayPrice: '0.00',
      firstPayPeopleNum: 1,
      firstPayPrice: '0.00',
      PayPeopleNum: 1,
      PayPrice: '0.00',
    },
    {
      channel: 'z10000001',
      activationPeopleNum: 0,
      registerPeopleNum: 0,
      registerFirstPayPeopleNum: 0,
      registerFirstPayPrice: '0.00',
      registerPayNum: 0,
      registerPayPrice: '0.00',
      firstPayPeopleNum: 0,
      firstPayPrice: '0.00',
      PayPeopleNum: 0,
      PayPrice: '0.00',
    },
  ],
};
