/* eslint-disable no-param-reassign */
import Layout from '../sys/views/layout/Layout.vue';
import { domain, valid } from './data';

const routes = [
  {
    path: '/tool',
    component: Layout,
    redirect: '/tool/upload-image',
    name: '工具管理',
    meta: { title: '工具管理', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: 'upload-image',
        component: () => import('../tool/upload-image/App'),
        name: '上传图片',
        meta: { title: '上传图片', noCache: true },
      },
      {
        path: 'upload-file',
        component: () => import('../tool/upload-file/App'),
        name: '上传文件',
        meta: { title: '上传文件', noCache: true },
      },
      {
        path: 'open-install-url',
        component: () => import('../tool/open-install-url/App'),
        name: '生成 OpenInstall 链接',
        meta: { title: '生成 OpenInstall 链接', noCache: true },
      },
    ],
  },
  {
    path: '/ling',
    component: Layout,
    controlMark: 'pw_yaolingling',
    redirect: '/ling/index',
    name: '要灵灵管理',
    meta: { title: '要灵灵管理', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: 'index',
        component: () => import('../ling/index/App'),
        name: '礼品管理',
        meta: { title: '礼品管理', noCache: true },
      },
      {
        path: 'edit/:id',
        component: () => import('../ling/edit/App'),
        name: '礼品添加 / 编辑',
        meta: { title: '礼品添加 / 编辑', noCache: true },
        hidden: !0,
      },
      {
        path: 'exchange',
        component: () => import('../ling/exchange/App'),
        name: '兑奖管理',
        meta: { title: '兑奖管理', noCache: true },
      },
      {
        path: 'gift',
        component: () => import('../ling/gift/App'),
        name: '暴富奖品',
        meta: { title: '暴富奖品', noCache: true },
      },
      {
        path: 'send',
        component: () => import('../ling/send/App'),
        name: '暴富发奖',
        meta: { title: '暴富发奖', noCache: true },
      },
      {
        path: 'bubble',
        component: () => import('../ling/bubble/App'),
        name: '气泡广告',
        meta: { title: '气泡广告', noCache: true },
      },
      {
        path: 'entry',
        component: () => import('../ling/entry/App'),
        name: '许愿入口',
        meta: { title: '许愿入口', noCache: true },
      },
      {
        path: 'fate',
        component: () => import('../ling/fate/App'),
        name: '好运攻略',
        meta: { title: '好运攻略', noCache: true },
      },
      {
        path: `${domain}/wish/marker`,
        name: '祈福牌管理',
        meta: { title: '祈福牌管理' },
      },
      {
        path: 'face',
        component: () => import('../ling/face/App'),
        name: '互动发言',
        meta: { title: '互动发言', noCache: true },
      },
    ],
  },
  {
    path: '/fubi',
    component: Layout,
    controlMark: 'pw_blesscoin',
    redirect: '/fubi/index',
    name: '福币分销',
    meta: { title: '福币分销', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: 'index',
        component: () => import('../fubi/index/App'),
        name: '福币商城',
        meta: { title: '福币商城', noCache: true },
      },
    ],
  },
  {
    path: '/promo',
    component: Layout,
    controlMark: 'pw_promo',
    redirect: '/promo/index',
    name: '运营事件',
    meta: { title: '运营事件', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: 'index',
        component: () => import('../promo/index/App'),
        name: '事件管理',
        meta: { title: '事件管理', noCache: true },
      },
      {
        path: 'index/transfer-list',
        component: () => import('../promo/index/App'),
        name: '事件管理 / 转单列表',
        meta: { title: '事件管理 / 转单列表', noCache: true },
        hidden: !0,
      },
      {
        path: 'statistics',
        component: () => import('../promo/statistics/App'),
        name: '事件统计',
        meta: { title: '事件统计', noCache: true },
      },
      {
        path: 'ci',
        component: () => import('../promo/ci/App'),
        name: '慈光计划',
        meta: { title: '慈光计划', noCache: true },
      },
      {
        path: 'topic',
        component: () => import('../promo/topic/App'),
        name: '专题管理',
        meta: { title: '专题管理', noCache: true },
      },
      {
        path: 'topicEdit/:id',
        component: () => import('../promo/topic_edit/App'),
        name: '专题列表 / 编辑专题',
        meta: { title: '专题列表 / 编辑专题', noCache: true },
        hidden: !0,
      },
      {
        path: 'topicCreate/:id',
        component: () => import('../promo/topic_edit/App'),
        name: '专题列表 / 新建专题',
        meta: { title: '专题列表 / 新建专题', noCache: true },
        hidden: !0,
      },
      {
        path: `${domain}/event/thousand`,
        name: '千寺祈福',
        meta: { title: '千寺祈福' },
      },
      {
        path: `${domain}/goods/index`,
        name: '自在好物',
        meta: { title: '自在好物' },
      },
      {
        path: 'transferSet/:id',
        component: () => import('../promo/transfer_set/App'),
        name: '转单系统 / 转单设置',
        meta: { title: '转单系统 / 转单设置', noCache: true },
        hidden: !0,
      },
      {
        path: 'mergeSet/:id',
        component: () => import('../promo/merge_set/App'),
        name: '转单系统 / 组合设置',
        meta: { title: '转单系统 / 组合设置', noCache: true },
        hidden: !0,
      },
      {
        path: 'buddhistEdit/:id',
        component: () => import('../promo/buddhist_edit/App'),
        name: '推广佛事 / 推广编辑',
        meta: { title: '推广佛事 / 推广编辑', noCache: true },
        hidden: !0,
      },
      {
        path: 'fubiRecord/:id',
        component: () => import('../promo/fubi_record/App'),
        name: '福币分享 / 记录',
        meta: { title: '福币分享 / 记录', noCache: true },
        hidden: !0,
      },
      {
        path: 'pay-pop',
        component: () => import('../promo/pay-pop/App'),
        name: '支付弹窗设置',
        meta: { title: '支付弹窗设置', noCache: true },
      },
    ],
  },
  {
    path: '/temple',
    component: Layout,
    redirect: '/temple/super',
    name: '寺院管理',
    meta: { title: '寺院管理', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: 'super',
        component: () => import('../temple/super/App'),
        name: '超级访问',
        meta: { title: '超级访问', noCache: true },
        controlMark: 'pw_temple',
      },
      {
        path: 'notice',
        component: () => import('../temple/notice/App'),
        name: '寺院通知',
        meta: { title: '寺院通知', noCache: true },
        controlMark: 'pw_temple',
      },
      {
        path: `${domain}/temple/verify`,
        name: '寺院审核',
        meta: { title: '寺院审核' },
        controlMark: 'pw_temple',
      },
      {
        path: `${domain}/temple/certification`,
        name: '寺院列表',
        meta: { title: '寺院列表' },
        controlMark: 'pw_temple',
      },
      {
        path: `${domain}/finance/verifyIndex`,
        name: '善款资料审核',
        meta: { title: '善款资料审核' },
        controlMark: 'pw_temple',
      },
      {
        path: 'comment',
        component: () => import('../temple/comment/App'),
        name: '评价管理',
        meta: { title: '评价管理', noCache: true },
        controlMark: 'pw_evaluation',
      },
      {
        name: '积分任务',
        path: 'integral-task',
        component: () => import('../temple/integral-task/App'),
        meta: { title: '积分任务', noCache: true },
        controlMark: 'pw_temple',
      },
      {
        name: '积分记录',
        path: 'integrate',
        component: () => import('../buddhist/integrate/App'),
        meta: { title: '积分记录', noCache: true },
        controlMark: 'pw_temple',
      },
    ],
  },
  {
    path: '/finance',
    component: Layout,
    redirect: '/finance/pending',
    name: '善款中心',
    meta: { title: '善款中心', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: 'pending',
        component: () => import('../finance/pending/App'),
        name: '待处理事项',
        meta: { title: '待处理事项', noCache: true },
        controlMark: 'pw_money',
      },
      {
        path: 'taking/:id',
        component: () => import('../finance/taking/App'),
        name: '提现账单详情',
        meta: { title: '提现账单详情', noCache: true },
        controlMark: 'pw_money',
        hidden: !0,
      },
      {
        path: `stat`,
        component: () => import('../finance/stat/App'),
        name: '善款统计',
        meta: { title: '善款统计', noCache: true },
        controlMark: 'pw_important_data',
      },
      {
        path: 'summary',
        component: () => import('../finance/summary/App'),
        name: '善款明细',
        meta: { title: '善款明细', noCache: true },
        controlMark: 'pw_money',
        hidden: !0,
      },
      {
        path: 'special',
        component: () => import('../finance/special/App'),
        name: '特殊提现',
        meta: { title: '特殊提现', noCache: true },
        controlMark: 'pw_money',
        hidden: !0,
      },
      {
        path: 'income-stat',
        component: () => import('../finance/income-stat/App'),
        name: '营收统计',
        meta: { title: '营收统计', noCache: true },
        controlMark: 'pw_important_data',
      },
      {
        path: 'income',
        name: '营收管理',
        component: () => import('../finance/income/App'),
        meta: { title: '营收管理', noCache: true },
        controlMark: 'pw_rate',
      },
      {
        path: 'record',
        name: '人工记账',
        component: () => import('../finance/record/App'),
        meta: { title: '人工记账', noCache: true },
        controlMark: 'pw_cash_income',
      },
      {
        path: 'remark',
        name: '提醒备注',
        component: () => import('../finance/remark/App'),
        meta: { title: '提醒备注', noCache: true },
        controlMark: 'pw_cash_remark',
      },
      {
        path: 'trade-stat',
        name: '交易统计',
        component: () => import('../finance/trade-stat/App'),
        meta: { title: '交易统计', noCache: true },
        controlMark: 'pw_cash_jing',
      },
    ],
  },
  {
    path: '/qu',
    component: Layout,
    controlMark: 'pw_funtop',
    redirect: '/qu/article',
    name: '趣头条管理',
    meta: { title: '趣头条管理', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: 'article',
        component: () => import('../qu/article/App'),
        name: '订阅文章列表',
        meta: { title: '订阅文章列表', noCache: true },
      },
      {
        path: 'material',
        component: () => import('../qu/material/App'),
        name: '素材库',
        meta: { title: '素材库', noCache: true },
      },
      {
        path: 'source',
        component: () => import('../qu/source/App'),
        name: '订阅源管理',
        meta: { title: '订阅源管理', noCache: true },
      },
    ],
  },
  {
    path: '/order',
    component: Layout,
    controlMark: 'pw_order',
    redirect: '/order/index',
    name: '订单管理',
    meta: { title: '订单管理', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: `${domain}/order/templeOrderList`,
        name: '寺院监控',
        meta: { title: '寺院监控' },
      },
      {
        path: `${domain}/orderManage/statisticsDetail`,
        name: '订单查询',
        meta: { title: '订单查询' },
      },
      {
        path: 'refund',
        component: () => import('../order/refund/App'),
        name: '退款记录',
        meta: { title: '退款记录', noCache: true },
      },
    ],
  },
  {
    path: '/stat',
    component: Layout,
    name: '数据统计 ',
    meta: { title: '数据统计', icon: 'fa-circle', noCache: true },
    children: [
      {
        name: '数据汇总',
        path: `${domain}/stat/sum`,
        meta: { title: '数据汇总' },
        controlMark: 'pw_statistics',
      },
      {
        name: '分析报表',
        path: `${domain}/stat/statisticsIndex`,
        meta: { title: '分析报表' },
        controlMark: 'pw_statistics',
      },
      {
        name: '模块数据',
        path: `${domain}/stat/statisticsIndex?type=module`,
        meta: { title: '模块数据' },
        controlMark: 'pw_statistics_module',
      },
      {
        name: '寺院数据',
        path: `${domain}/stat/templeIndex`,
        meta: { title: '寺院数据' },
        controlMark: 'pw_important_data',
      },
      {
        name: '佛事数据',
        path: `${domain}/stat/buddishData`,
        meta: { title: '佛事数据' },
        controlMark: 'pw_statistics',
      },
      {
        name: '推广数据',
        path: `${domain}/stat/promoIndex`,
        meta: { title: '推广数据' },
        controlMark: 'pw_statistics',
      },
      {
        name: '渠道统计',
        component: () => import('../statistics/channel/App'),
        path: 'channel',
        meta: { title: '渠道统计' },
        controlMark: 'pw_promo',
      },
      {
        path: 'detail/:channel/:channelId/:addTime',
        component: () => import('../statistics/detail/App'),
        name: '渠道统计详情',
        meta: { title: '渠道统计详情', noCache: true },
        hidden: !0,
      },
    ],
  },
  {
    path: '/wish',
    component: Layout,
    name: '法师模块',
    meta: { title: '法师模块', icon: 'fa-circle', noCache: true },
    children: [
      {
        path: 'project',
        component: () => import('../master/project/App'),
        name: '加持项目',
        meta: { title: '加持项目', noCache: true },
        controlMark: 'pw_wish',
      },
      {
        path: 'edit/:name',
        component: () => import('../master/edit/App'),
        name: '编辑项目',
        meta: { title: '编辑项目', noCache: true },
        controlMark: 'pw_wish',
        hidden: !0,
      },
      {
        path: 'support-manege',
        name: '供养管理',
        component: () => import('../master/support-manege/App'),
        meta: { title: '供养管理', noCache: true },
        controlMark: ['pw_wish', 'pw_money'],
      },
      {
        name: '加持订单',
        path: `${domain}/wish/plus`,
        meta: { title: '加持订单' },
        controlMark: 'pw_wish',
      },
      {
        name: '法师管理',
        path: `${domain}/wish/master`,
        meta: { title: '法师管理' },
        controlMark: 'pw_wish',
      },
      {
        name: '心愿管理',
        path: `${domain}/wish/index`,
        meta: { title: '心愿管理' },
        controlMark: 'pw_wish',
      },
      {
        name: '还愿管理',
        path: `${domain}/wish/return`,
        meta: { title: '还愿管理' },
        controlMark: 'pw_wish',
      },
      {
        name: '寺院认证',
        path: `${domain}/wish/verify`,
        meta: { title: '寺院认证' },
        controlMark: 'pw_wish',
      },
      {
        name: '经咒落地页管理',
        path: `${domain}/wish/template`,
        meta: { title: '经咒落地页管理' },
        controlMark: 'pw_wish',
      },
    ],
  },
  {
    path: '/buddhist',
    component: Layout,
    name: '佛事管理',
    meta: { title: '佛事管理', icon: 'fa-circle', noCache: true },
    children: [
      {
        name: '佛事审核',
        path: `${domain}/buddhist/verify`,
        meta: { title: '佛事审核' },
        controlMark: 'pw_ceremony',
      },
      {
        name: '佛事模板',
        path: `${domain}/buddhist/template`,
        meta: { title: '佛事模板' },
        controlMark: 'pw_ceremony',
      },
      {
        name: '佛事分类',
        path: `${domain}/buddhist/classification`,
        meta: { title: '佛事分类' },
        controlMark: 'pw_ceremony',
      },
      {
        name: '佛事标签',
        path: `${domain}/buddhist/tag`,
        meta: { title: '佛事标签' },
        controlMark: 'pw_ceremony',
      },
    ],
  },
  {
    path: '/ad',
    component: Layout,
    name: '广告管理',
    meta: { title: '广告管理', icon: 'fa-circle', noCache: true },
    children: [
      {
        name: '佛事推荐',
        path: `${domain}/ad/buddhist`,
        meta: { title: '佛事推荐' },
        controlMark: 'pw_advertising',
      },
      {
        path: 'system-popup',
        name: '系统广告',
        component: () => import('../ad/system-popup/App'),
        meta: { title: '系统广告', noCache: true },
      },
    ],
  },
];

const first = routes.filter(item => valid(item));

first.forEach(item => {
  const { children } = item;
  item.children = children.filter(subItem => valid(subItem));
});

export default first.filter(item => item.children && item.children.length);
