export const list = {
  msg: '',
  errorCode: 0,
  data: {
    list: [
      {
        id: 38105,
        name: ' 2017年相约锦林 传灯法会 护持登记表',
        money: 9.99,
        addTime: '2017-02-19 23:08:45',
        postscript: [
          {
            name: '功德芳名',
            value: '佛弟子',
            type: 6,
            inputId: '#customInput17078',
          },
        ],
        order_number: 38105,
        outer_order_number: 'H9nLxxY4rps6VKHs1487516924',
        running_number: '4003692001201702190585340216',
        urgeOrder: 0,
        buyNum: 1,
        dispose_pic_url: '',
        user: {
          name: '且行且修',
          mobile: '',
          address: '佛弟子',
        },
      },
      {
        id: 38080,
        name: ' 2017年相约锦林 传灯法会 护持登记表',
        money: 100,
        addTime: '2017-02-19 22:41:39',
        postscript: [
          {
            name: '功德芳名',
            value: '善信',
            type: 6,
            inputId: '#customInput17075',
          },
        ],
        order_number: 38080,
        outer_order_number: 'OLf5dGUwxbrnARXx1487515299',
        running_number: '4002872001201702190582239970',
        urgeOrder: 0,
        buyNum: 1,
        dispose_pic_url: '',
        user: {
          name: '锦林寺客堂',
          mobile: '',
          address: '善信',
        },
      },
    ],
    total: 2,
  },
};

export const activityList = {
  msg: '',
  errorCode: 0,
  data: {
    count: 2,
    list: [
      {
        id: 1278,
        name: '[1278]广东揭西锦林寺第四届49天历代婴灵解脱法会通启',
        shop_id: 22,
        commodity_type_id: 116,
        stock: -1,
        price: -1,
        add_time: '05-08 18:57:44',
        op_status: 0,
        is_show_participant: 1,
        is_end: 1,
        random_money_list: '',
        end_time: '07-13 00:00:12',
        join_num: 0,
        collect_money: 0,
        type: 1,
        is_show_time: 0,
        is_show_cnt: 0,
        is_need_pay: 0,
        is_auto_finish: 0,
        start_time: '05-08 18:57:44',
        printer_id: '0',
        is_open_printer: 0,
        continuous_print_num: 2,
        qrcode_print: 0,
        is_conversion: 0,
        temple_id: 27,
        notConversionOrderNum: 0,
        conversionOrderNum: 0,
        conversionOrderPrice: 0,
        profitConversionOrderPrice: 0,
        targetAmount: 0,
        isPromotion: 0,
        serviceMoney: 0,
        promotionPercentage: 0,
        isOnlyChanzai: 0,
        isPrivate: 0,
        promotionMoney: 0,
        shareBlessCoin: 0,
        shareBlessCoinPayCnt: 0,
        shareBlessCoinPay: 0,
        blessCoinSort: 0,
        userAllowType: 0,
        userGroupId: 0,
        view_count: 0,
        sharePic: '',
        content: '',
        existManege: 0,
        managerNames: '',
        editTime: '',
        templeId: 27,
        templeName: '揭西锦林寺',
        tagList: [],
        subList: [
          {
            id: 1705,
            name: '消灾延寿牌位',
            isHandlingFee: 0,
            price: -1,
            conversionSubdivide: 0,
            isConversion: 0,
            wishOrderMoney: 0,
          },
          {
            id: 1706,
            name: '婴灵超度牌位',
            isHandlingFee: 0,
            price: -1,
            conversionSubdivide: 0,
            isConversion: 0,
            wishOrderMoney: 0,
          },
          {
            id: 1707,
            name: '祖先超度牌位',
            isHandlingFee: 0,
            price: -1,
            conversionSubdivide: 0,
            isConversion: 0,
            wishOrderMoney: 0,
          },
          {
            id: 1708,
            name: '冤亲债主牌位',
            isHandlingFee: 0,
            price: -1,
            conversionSubdivide: 0,
            isConversion: 0,
            wishOrderMoney: 0,
          },
        ],
        url:
          'https://wx.zizaihome.com/commodity/commodityInfo?commodityId=1278',
      },
      {
        id: 271,
        name: '[271] 2017年相约锦林 传灯法会 护持登记表',
        shop_id: 22,
        commodity_type_id: 124,
        stock: -1,
        price: -1,
        add_time: '02-19 20:15:28',
        op_status: 0,
        is_show_participant: 1,
        is_end: 0,
        random_money_list: '',
        end_time: '12-31 00:00:00',
        join_num: 2,
        collect_money: 109.99,
        type: 1,
        is_show_time: 0,
        is_show_cnt: 1,
        is_need_pay: 0,
        is_auto_finish: 0,
        start_time: '02-19 20:15:28',
        is_open_printer: 0,
        continuous_print_num: 0,
        qrcode_print: 0,
        is_conversion: 0,
        temple_id: 27,
        notConversionOrderNum: 0,
        conversionOrderNum: 0,
        conversionOrderPrice: 0,
        profitConversionOrderPrice: 0,
        targetAmount: 0,
        isPromotion: 0,
        serviceMoney: 0,
        promotionPercentage: 0,
        isOnlyChanzai: 0,
        isPrivate: 0,
        promotionMoney: 0,
        shareBlessCoin: 0,
        shareBlessCoinPayCnt: 0,
        shareBlessCoinPay: 0,
        blessCoinSort: 0,
        userAllowType: 0,
        userGroupId: 0,
        view_count: 0,
        sharePic: '',
        content: '',
        existManege: 0,
        managerNames: '',
        editTime: '',
        templeId: 27,
        templeName: '揭西锦林寺',
        tagList: [],
        subList: [
          {
            id: 980,
            name: '供平安灯',
            isHandlingFee: 0,
            price: -1,
            conversionSubdivide: 0,
            isConversion: 0,
            wishOrderMoney: 0,
          },
          {
            id: 981,
            name: '供智慧灯',
            isHandlingFee: 0,
            price: -1,
            conversionSubdivide: 0,
            isConversion: 0,
            wishOrderMoney: 0,
          },
          {
            id: 982,
            name: '供添丁灯',
            isHandlingFee: 0,
            price: -1,
            conversionSubdivide: 0,
            isConversion: 0,
            wishOrderMoney: 0,
          },
        ],
        url: 'https://wx.zizaihome.com/commodity/commodityInfo?commodityId=271',
      },
    ],
  },
};
