export const list = {
  msg: '',
  errorCode: 0,
  data: [
    {
      id: '27',
      count3: '0',
      count2: '2',
      count: '2',
      templeName: '揭西锦林寺',
      days: 0,
    },
    {
      id: '5591',
      count3: '82',
      count2: '2671',
      count: '2731',
      days: '1',
      templeName: '自在家',
    },
    {
      id: '5595',
      count3: '0',
      count2: '1',
      count: '1',
      days: '1004',
      templeName: '杭州石盂寺',
    },
    {
      id: '5605',
      count3: '0',
      count2: '23',
      count: '23',
      days: '1004',
      templeName: '深圳般若禅寺',
    },
    {
      id: '5613',
      count3: '0',
      count2: '3',
      count: '3',
      days: '1004',
      templeName: '宁津普渡寺',
    },
    {
      id: '5646',
      count3: '0',
      count2: '2',
      count: '2',
      templeName: '新丰西莲寺',
      days: 0,
    },
    {
      id: '5647',
      count3: '0',
      count2: '1',
      count: '1',
      templeName: '通化神龙禅寺',
      days: 0,
    },
    {
      id: '5657',
      count3: '0',
      count2: '12',
      count: '12',
      days: '1004',
      templeName: '长沙市大安寺',
    },
    {
      id: '5663',
      count3: '1',
      count2: '8',
      count: '8',
      days: '1004',
      templeName: '腾冲市腾越镇洞坪社区天应寺',
    },
    {
      id: '5666',
      count3: '3',
      count2: '16',
      count: '16',
      templeName: '金川区法云寺',
      days: 0,
    },
    {
      id: '5676',
      count3: '1',
      count2: '1',
      count: '1',
      days: '1004',
      templeName: '介休市祥云寺',
    },
    {
      id: '5687',
      count3: '0',
      count2: '1',
      count: '1',
      days: '1004',
      templeName: '灵宝寺',
    },
    {
      id: '5688',
      count3: '0',
      count2: '7',
      count: '7',
      days: '1004',
      templeName: '遂宁市普照寺',
    },
    {
      id: '5722',
      count3: '0',
      count2: '9',
      count: '9',
      days: '8',
      templeName: '自在好物（妙严）',
    },
    {
      id: '5734',
      count3: '0',
      count2: '1',
      count: '1',
      templeName: '昆明石林杏林禅寺',
      days: 0,
    },
    {
      id: '5739',
      count3: '0',
      count2: '3',
      count: '3',
      days: '1004',
      templeName: '泰州古千佛寺',
    },
    {
      id: '5754',
      count3: '0',
      count2: '1',
      count: '1',
      templeName: '浙江温州圆明寺',
      days: 0,
    },
    {
      id: '5772',
      count3: '0',
      count2: '1',
      count: '1',
      templeName: '观音山观音寺',
      days: 0,
    },
    {
      id: '5774',
      count3: '0',
      count2: '2',
      count: '2',
      days: '86',
      templeName: '重庆天心寺',
    },
    {
      id: '5822',
      count3: '0',
      count2: '1',
      count: '1',
      templeName: '云南蒙自金坡寺',
      days: 0,
    },
    {
      id: '5899',
      count3: '0',
      count2: '5',
      count: '5',
      days: '794',
      templeName: '安徽淮南北洞山观音寺',
    },
    {
      id: '5925',
      count3: '0',
      count2: '5',
      count: '5',
      days: '57',
      templeName: '建瓯定光寺',
    },
    {
      id: '5996',
      count3: '1',
      count2: '1',
      count: '1',
      days: '785',
      templeName: '河南嵩山中岳庙',
    },
    {
      id: '6062',
      count3: '0',
      count2: '10',
      count: '10',
      days: '991',
      templeName: '深圳齐善素食食品有限公司',
    },
    {
      id: '6072',
      count3: '0',
      count2: '4',
      count: '4',
      templeName: '西峡燃灯寺',
      days: 0,
    },
    {
      id: '6090',
      count3: '0',
      count2: '1',
      count: '1',
      templeName: '古田报慈寺',
      days: 0,
    },
    {
      id: '6137',
      count3: '0',
      count2: '1',
      count: '1',
      templeName: '朝阳大真如寺',
      days: 0,
    },
    {
      id: '6320',
      count3: '0',
      count2: '1',
      count: '1',
      days: '22',
      templeName: '自在好物（胜乐）',
    },
    {
      id: '6372',
      count3: '0',
      count2: '29',
      count: '49',
      days: '1',
      templeName: '名山推荐',
    },
    {
      id: '6439',
      count3: '0',
      count2: '1',
      count: '1',
      days: '315',
      templeName: '迈法师',
    },
    {
      id: '6448',
      count3: '0',
      count2: '3',
      count: '3',
      templeName: '芬陀利华',
      days: 0,
    },
    {
      id: '6482',
      count3: '3',
      count2: '38',
      count: '38',
      days: '3',
      templeName: '活动推荐',
    },
    {
      id: '6590',
      count3: '7',
      count2: '190',
      count: '238',
      days: '1',
      templeName: '自在好物',
    },
  ],
};
