export const cacheList = {
  msg: '',
  errorCode: 0,
  data: {
    count: 499,
    list: [
      {
        add_time: '11-05 17:02:32',
        blessCoinSort: 0,
        collect_money: 0,
        commodity_type_id: 152,
        content: '',
        continuous_print_num: 2,
        conversionOrderNum: 0,
        conversionOrderPrice: 0,
        editTime: '11-08 19:01:13',
        end_time: '12-31 23:59:00',
        existManege: 1,
        id: 9197,
        isOnlyChanzai: 0,
        isPrivate: 0,
        isPromotion: 0,
        is_auto_finish: 1,
        is_conversion: 0,
        is_end: 0,
        is_need_pay: 0,
        is_open_printer: 0,
        is_show_cnt: 1,
        is_show_participant: 1,
        is_show_time: 0,
        join_num: 0,
        managerNames:
          '??,哈法师,苏诱仁波切,影子影子影子你在哪里呀！！？？？？？？？？？,TRAIN-TRAIN,环保法师,麦法师',
        name: '[9197]佛事海报测试（2021-12-31）结束一二三四五六七八九十',
        notConversionOrderNum: 0,
        op_status: 1,
        price: -1,
        printer_id: '0',
        profitConversionOrderPrice: 0,
        promotionMoney: 0,
        promotionPercentage: 0,
        qrcode_print: 0,
        random_money_list: '',
        serviceMoney: 0,
        shareBlessCoin: 0,
        shareBlessCoinPay: 0,
        shareBlessCoinPayCnt: 0,
        sharePic: '',
        shop_id: 0,
        start_time: '10-25 10:20:29',
        stock: -1,
        subList: [
          {
            blessWishPrompt: '',
            conversionSubdivide: 0,
            id: 35442,
            isConversion: 0,
            isHandlingFee: 1,
            name: '普通佛事1',
            price: 100,
            wishOrderMoney: 0,
          },
          {
            blessWishPrompt: '',
            conversionSubdivide: 0,
            id: 35443,
            isConversion: 0,
            isHandlingFee: 0,
            name: '普通佛事2',
            price: 200,
            wishOrderMoney: 0,
          },
        ],
        tagList: [],
        targetAmount: 0,
        templeId: 4,
        templeName: '寺院管理后台',
        temple_id: 4,
        type: 1,
        url:
          'https://wx.zizaihome.com/commodity/commodityInfo?commodityId=9197',
        userAllowType: 0,
        userGroupId: 0,
        view_count: 3,
      },
    ],
    pageSum: 24,
  },
};

export const templeList = {
  errorCode: 0,
  msg: '',
  data: [
    {
      add_time: '2022-02-22 14:36:18',
      allowOp: 1,
      chanzai_latitude: 0,
      chanzai_longitude: 0,
      city: '',
      conversionOrderNum: 0,
      conversionOrderPrice: 0,
      district: '',
      id: 6215,
      introduce: '',
      isShowGongdeBoxPrice: 1,
      isTest: 0,
      is_offline: 0,
      managertList: [],
      name: '后台申请',
      placeType: 1,
      profitConversionOrderPrice: 0,
      province: '',
      show_website_abbot_suixi: 1,
      show_website_scenes_suixi: 1,
      show_website_suixi: 1,
      specialPickUpNum: 2,
      tagList: [],
      templeMonthlyReportUrl:
        'http://wx.zizaihome.com/templeMonthlyReport/templeMonthlyReport?templeIdStr=MzAzMzAxMzA1NDAy&isTest=1',
      url:
        'https://wxapp1.zizaihome.com/commodity/templateWebsiteInfo?templeId=6215&isTest=1',
      verify: 0,
      vr_gift_finance_percent: 0.01,
      website_visit_num: 0,
    },
  ],
};

export const commodityList = {
  errorCode: 0,
  msg: '',
  data: {
    count: 4400,
    list: [
      {
        account: '',
        id: 1,
        name: '【1】供奉长生禄位',
        templeId: 1,
        templeName: '深圳弘法寺(测试)',
      },
    ],
  },
};

export const auth = {
  errorCode: 0,
  msg: '',
};

export const opruleList = {
  msg: '',
  errorCode: 0,
  data: [
    {
      id: 11,
      userType: 2,
      provinceJson: '',
      cityJson: '',
      registerTime: -1,
      ruleJson: [
        {
          days: 2,
          symbol: 1,
          ruleName: 'startApp',
        },
      ],
      name: '小易测试',
      addTime: '2019-12-30 11:07',
      status: 0,
      ruleType: 1,
      total: 0,
      wxtagId: 0,
      default_userId: '',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=11',
    },
    {
      id: 12,
      userType: 1,
      provinceJson: {
        symbol: 1,
        province: '广东省,北京市',
      },
      cityJson: '',
      registerTime: -1,
      ruleJson: [],
      name: '用户分群微信端测试',
      addTime: '2020-01-08 14:00',
      status: 0,
      ruleType: 1,
      total: 0,
      wxtagId: 0,
      default_userId: '',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=12',
    },
    {
      id: 13,
      userType: 2,
      provinceJson: '',
      cityJson: '',
      registerTime: -1,
      ruleJson: [],
      name: '用户分群APP端测试',
      addTime: '2020-01-08 14:03',
      status: 0,
      ruleType: 2,
      total: 0,
      wxtagId: 0,
      default_userId: '',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=13',
    },
    {
      id: 14,
      userType: 0,
      provinceJson: '',
      cityJson: '',
      registerTime: -1,
      ruleJson: [],
      name: '2345',
      addTime: '2020-05-08 11:31',
      status: 0,
      ruleType: 0,
      total: 0,
      wxtagId: 0,
      default_userId: '',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=14',
    },
    {
      id: 16,
      userType: 0,
      provinceJson: {
        symbol: 1,
        province: '青海省',
      },
      cityJson: {
        symbol: 1,
        city: '唐山市',
      },
      registerTime: 100,
      registerTimeStart: '',
      registerTimeEnd: '',
      ruleJson: [
        {
          startDate: '2022-03-03',
          endDate: '2022-03-10',
          type: 2,
          contentId: '4,6',
          symbol: 4,
          number: 10,
          number2: 100,
          ruleName: 'paySuccess',
        },
        {
          days: 10,
          type: 2,
          contentId: '5,6',
          symbol: 4,
          number: 10,
          number2: 100,
          ruleName: 'payMoney',
        },
        {
          days: 100,
          symbol: 1,
          ruleName: 'startApp',
        },
      ],
      name: '12341',
      addTime: '2020-05-08 18:26',
      status: 0,
      ruleType: 2,
      total: 0,
      wxtagId: 0,
      default_userId: '',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=16',
    },
    {
      id: 18,
      userType: 0,
      provinceJson: '',
      cityJson: '',
      registerTime: -1,
      ruleJson: [],
      name: '藏传佛事消费用户>=10元',
      addTime: '2021-03-29 18:05',
      status: 0,
      ruleType: 1,
      total: 3587,
      wxtagId: 0,
      default_userId: '',
      count: 3587,
      downloadUrl: '/oprule/downloadExcel?ruleId=18',
    },
    {
      id: 19,
      userType: 2,
      provinceJson: '',
      cityJson: '',
      registerTime: -1,
      ruleJson: [],
      name: 'APP后端在测试',
      addTime: '2020-01-08 14:03',
      status: 0,
      ruleType: 2,
      total: 0,
      wxtagId: 0,
      default_userId: '1000064199',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=19',
    },
    {
      id: 220,
      userType: 0,
      provinceJson: '',
      cityJson: '',
      registerTime: -1,
      ruleJson: [],
      name: '[菜单]离职员工',
      addTime: '2021-10-26 16:08',
      status: 0,
      ruleType: 1,
      total: 139,
      wxtagId: 135,
      default_userId: '',
      count: 139,
      downloadUrl: '/oprule/downloadExcel?ruleId=220',
    },
    {
      id: 222,
      userType: 0,
      provinceJson: {
        symbol: 1,
        province: '河北省',
      },
      cityJson: {
        symbol: 0,
        city: '唐山市',
      },
      registerTime: 0,
      registerTimeStart: '2022-03-03',
      registerTimeEnd: '2022-03-08',
      ruleJson: [
        {
          days: 14,
          type: 0,
          contentId: '4,6',
          symbol: 1,
          number: 14,
          number2: 0,
          ruleName: 'paySuccess',
        },
        {
          days: 12,
          type: 0,
          contentId: '5,6',
          symbol: 3,
          number: 22,
          number2: 0,
          ruleName: 'payMoney',
        },
        {
          startDate: '2022-03-04',
          endDate: '2022-03-09',
          symbol: 0,
          ruleName: 'startApp',
        },
      ],
      name: '测试',
      addTime: '2022-03-04 10:35',
      status: 0,
      ruleType: 2,
      total: 0,
      wxtagId: 0,
      default_userId: '',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=222',
    },
    {
      id: 224,
      userType: 0,
      provinceJson: {
        symbol: 1,
        provinceList: ['北京市', '天津市'],
        province: '北京市,天津市',
      },
      cityJson: {
        symbol: 1,
        cityList: ['石家庄', '邯郸'],
        city: '石家庄,邯郸',
      },
      registerTime: 101,
      registerTimeStart: '',
      registerTimeEnd: '',
      ruleJson: [
        {
          days: '4',
          type: 0,
          contentId: '',
          symbol: 4,
          number: '1',
          number2: '4',
          ruleName: 'paySuccess',
          dateType: 1,
          ruleNameText: '支付成功',
        },
      ],
      name: 'ces',
      addTime: '2022-03-07 12:14',
      status: 0,
      ruleType: 2,
      total: 0,
      wxtagId: 0,
      default_userId: '',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=224',
    },
    {
      id: 226,
      userType: 0,
      provinceJson: '',
      cityJson: '',
      registerTime: -1,
      registerTimeStart: '',
      registerTimeEnd: '',
      ruleJson: [],
      name: '1111',
      addTime: '2022-03-08 15:30',
      status: 0,
      ruleType: 2,
      total: 0,
      wxtagId: 0,
      default_userId: '12341234',
      count: 0,
      downloadUrl: '/oprule/downloadExcel?ruleId=226',
    },
  ],
};

export const commoditySubdivideList = {
  msg: '',
  errorCode: 0,
  data: [
    {
      id: 35390,
      name: '祈福牌位-一个名20个心愿',
      price: -1,
      isPromotion: 0,
      promotionMoney: 0,
    },
    {
      id: 35391,
      name: '祈福牌位-一个名200心愿',
      price: -1,
      isPromotion: 0,
      promotionMoney: 0,
    },
    {
      id: 35392,
      name: '祈福牌位-六个名20心愿',
      price: -1,
      isPromotion: 0,
      promotionMoney: 0,
    },
    {
      id: 35393,
      name: '祈福牌位-六个名200心愿',
      price: -1,
      isPromotion: 0,
      promotionMoney: 0,
    },
    {
      id: 35394,
      name: '往生牌位-一个往生者',
      price: -1,
      isPromotion: 0,
      promotionMoney: 0,
    },
    {
      id: 35395,
      name: '往生牌位-六个往生者',
      price: -1,
      isPromotion: 0,
      promotionMoney: 0,
    },
    {
      id: 35396,
      name: '祈福牌位-六个名50心愿',
      price: -1,
      isPromotion: 0,
      promotionMoney: 0,
    },
  ],
};

export const commodityManagerList = {
  msg: '',
  errorCode: 0,
  data: [
    {
      id: 1002,
      userId: 1000074398,
      headImg: 'http://imgs.zizaihome.com/1504762284362.jpg',
      nickName: '??',
      isManager: 1,
      subList: [
        {
          id: 35390,
          name: '祈福牌位-一个名20个心愿',
        },
      ],
    },
    {
      id: 100,
      userId: 666818,
      headImg: 'http://imgs.zizaihome.com/43ccfa163a31e6c911bc805cc62e367c.jpg',
      nickName: '哈法师',
      isManager: 0,
      subList: [],
    },
    {
      id: 133,
      userId: 1000064199,
      headImg: 'http://imgs.zizaihome.com/8d8babdda5c44674f83f0ff39927d4f1.gif',
      nickName: '苏诱仁波切',
      isManager: 0,
      subList: [],
    },
    {
      id: 273,
      userId: 1000220757,
      headImg:
        'http://imgs.zizaihome.com/0029e180-faa3-46ab-be71-8dc9a4b836bd.jpg',
      nickName: '影子影子影子你在哪里呀！！？？？？？？？？？',
      isManager: 0,
      subList: [],
    },
    {
      id: 406,
      userId: 1000844200,
      headImg:
        'http://imgs.zizaihome.com/e85e6899-e5bc-43b5-912d-597e5406c7f0.jpg',
      nickName: 'TRAIN-TRAIN',
      isManager: 1,
      subList: [],
    },
    {
      id: 408,
      userId: 1000843843,
      headImg: 'http://imgs.zizaihome.com/3ed560b63bb5e027d3510f10a2b4229b.jpg',
      nickName: '环保法师',
      isManager: 1,
      subList: [],
    },
    {
      id: 410,
      userId: 1000843838,
      headImg:
        'http://imgs.zizaihome.com/d14ea56a-2743-4987-8abe-4d5d9c9ae173.jpg',
      nickName: '麦法师',
      isManager: 1,
      subList: [],
    },
  ],
};
